### ISSUE TITLE
TypeError: Cannot read property 'undefinedelement' of undefined

### ISSUE THREAD

**Issue by Zenitram-Oriaj** [holidayextras/wsdl2.js#16]
I get this error when I try to convert my wsdl file:

```
/usr/local/lib/node_modules/wsdl2.js/wsdl2.js:300
    var elements = thisSchema[ns['xsd']+'element'];
                             ^
TypeError: Cannot read property 'undefinedelement' of undefined
    at /usr/local/lib/node_modules/wsdl2.js/wsdl2.js:300:30
    at Array.forEach (native)
    at processTypes (/usr/local/lib/node_modules/wsdl2.js/wsdl2.js:297:14)
    at processWSDL (/usr/local/lib/node_modules/wsdl2.js/wsdl2.js:94:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/wsdl2.js/wsdl2.js:79:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

```

The file passes validation using an online WSDL Validator

You can download the wsdl files from here:
https://www.dropbox.com/sh/td5iil3qb2k07tm/AABvhEO4EffLOKzh1IIZ4k0Ea?dl=0
(Note: the gws.wsdl file is a compiled version in where I imported the external xsd files. The folder called "Pre-Compiled" contains the original files. So use either.)

Let me know if you need anything else.

**Comment by shackpank** [comment]
Hi @Zenitram-Oriaj -- Thanks for the example! It's a great test case for XSD imports.

We will look at this eventually, but we don't need that feature at the moment so will probably not implement it any time soon.

**Comment by miopa** [comment]
I have the same issue. The problem seems to be in the way the app is handling the namespaces.

@Zenitram-Oriaj you can work-around the issue by moving the `xmlns:xs` namespace from `<xs:schema>` to `xmlns:xsd` in `<definitions>` and replace `xs:` prefix with `xsd:`
